//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://m.facebook.com/login.php?refsrc=http%3A%2F%2Fm.facebook.com%2Findex.php&amp;refid=8
        ///email={{username}}
        ///pass={{password}}
        ///lsd=AVrMdhYE
        ///charset_test=€,´,€,´,水,Д,Є
        ///version=1
        ///ajax=1
        ///width=1920
        ///pxr=1
        ///gps=1
        ///m_ts=1358832742
        ///li=ZiT-UIWK8L6q0qNMGoz6tT7I
        ///signup_layout=layout|lower_subdued_button||s_btn|special||l_btn|confirm||signupinstr||logininstr
        ///laststage=first
        ///login=Log In.
        /// </summary>
        internal static string facebook_login {
            get {
                return ResourceManager.GetString("facebook_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://m.facebook.com/login.php?refsrc=https%3A%2F%2Fm.facebook.com%2Fsettings%2Faccount%2F&amp;refid=70
        ///old_password={{oldpassword}}
        ///new_password={{newpassword}}
        ///confirm_password={{newpassword}}
        ///change_password=
        ///save=Change Password
        ///charset_test=€,´,€,´,水,Д,Є.
        /// </summary>
        internal static string facebook_passgate {
            get {
                return ResourceManager.GetString("facebook_passgate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{url}}/login2/
        ///user={{username}}
        ///passwrd={{password}}.
        /// </summary>
        internal static string smf_login {
            get {
                return ResourceManager.GetString("smf_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{url}}/profile/?area=account;u=1;save
        ///passwrd1={{newpassword}}
        ///passwrd2={{newpassword}}
        ///oldpasswrd={{oldpassword}}.
        /// </summary>
        internal static string smf_passgate {
            get {
                return ResourceManager.GetString("smf_passgate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mobile.twitter.com/session
        ///username={{username}}
        ///password={{password}}.
        /// </summary>
        internal static string twitter_login {
            get {
                return ResourceManager.GetString("twitter_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mobile.twitter.com/settings/password
        ///settings[current_password]={{oldpassword}}
        ///settings[password]={{newpassword}}
        ///settings[password_confirmation]={{newpassword}}.
        /// </summary>
        internal static string twitter_passgate {
            get {
                return ResourceManager.GetString("twitter_passgate", resourceCulture);
            }
        }
    }
}
